server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: authfordge-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authfordge
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 9f0f63001@smtp-brevo.com
    password: xsmtpsib-1c465e61cfafde1e1dc6e53557e66558fa0b415466ff301f83e7d4fde7a019e9-wDCfPBCk12ZJKvAD
    properties:
      mail:
        smtp:
          from: aayushkodan@gmail.com
          auth: true
          starttls:
            enable: true
    protocol: smtp

security:
  jwt:
    secret: ${JWT_SECRET:myJwtSecretKeyIsVerySecureAndLongEnoughForHS256AlgorithmWithAtLeast32Bytes512bitsMyApp2026DelhiStudentProjectVanLifeAPI}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}
